--

- name: Testing importing group and host vars via Tower
  hosts: all
  gather_facts: no
  connection: local

  environment:
    F5_SERVER: "{{ ansible_host }}"
    F5_USER: "admin"
    F5_PASSWORD: "admin"
    F5_VALIDATE_CERTS: no

  tasks:
    - name: Setting the hostname of the target BIGIP
      bigip_hostname:
        hostname: "{{ hostname }}"
